### ISSUE TITLE
Happy desk not working

### ISSUE THREAD

**Issue by dgrodrigues-hovione** [ihs7/wordcloud-pages#1]
Hello,

I've installed Happy desk in my jira cloud envirnoment and it is not working.
Created a ticket with customer only account and no score is provided.

Example:

![image](https://github.com/ihs7/wordcloud-pages/assets/146210453/7199fa01-df18-4c22-871b-ab5de2e97b2f)

![image](https://github.com/ihs7/wordcloud-pages/assets/146210453/ac1348fb-5586-44ad-9f04-ca81df650716)

![image](https://github.com/ihs7/wordcloud-pages/assets/146210453/f723b2ad-5209-4b3d-8827-33f2b02cf786)

![image](https://github.com/ihs7/wordcloud-pages/assets/146210453/7ad41ee8-6b99-452d-84cb-24ab7484a8b0)

**Comment by ihs7** [comment]
Hello @dgrodrigues-hovione! I'm looking into this issue.

From perspective of Jira REST APIs, when customer is licensed but assigned the group role 'Customer' in a certain project we still get `accountType` = `atlassian` from their APIs, until now I've been using `accountType` = `customer` to determine whether we should consider the sentiment source.

I think this is a completely valid use case for ITSM managed projects, for example where developers are assigned customer role in a project even though they are holding a license.

I'm looking into this, hopefully I can adjust the product so it works for this use case. Stay tuned!

**Comment by ihs7** [comment]
@dgrodrigues-hovione, I deployed a new version of the app which makes a few changes.

By default we now fetch public service desk content instead of narrowing in on the Atlassian customer accountType in the response. There is now a drop-down in the Overview and Dashboards that allow you to filter between these modes (Only Service Desk Content, Only External Customer Content, All Content).

Will be following up with improvement to the issue view so we can differentiate between creator and responders. 

Hope this helps!
